#   Copyright (c) Code Written and Tested by Ahmed Emad in 01/03/2020, 20:06
#

# Generated by Django 2.2.7 on 2020-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20200229_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
