#   Copyright (c) Code Written and Tested by Ahmed Emad in 02/03/2020, 16:29
#

# Generated by Django 3.0.3 on 2020-03-02 10:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200301_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoattachmentmodel',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_upload, validators=[core.models.filesize]),
        ),
    ]
